topics:
  - /sensor_time/events
  - /sensor_time/mcu_trigger
  - /sensor_time/mcu_pps
  - /sensor_time/gnss_pps_capture
  - /sensor_time/mapping
  - /sensor_time/status
  - /gnss/raw
  - /ublox_driver/receiver_pvt
  - /uwb/raw
  - /livox/lidar
  - /livox/imu
  - /left_camera/image
